# Generated by Django 5.1.5 on 2025-03-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='max_spend',
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
